Add Email Confirmation Service
zimajava/dev-ed-java-spec pull request #11
Opened 2020-12-04 16:21 UTC by dariiaKaptiurova

2020-12-04 16:57 UTC, jtfactum approved these changes

2020-12-04 16:59 UTC, Esochka180320 approved these changes

2020-12-04 17:08 UTC, Val-Zozulia-228 approved these changes

2020-12-04 17:56 UTC, jtfactum approved these changes

2020-12-05 19:26 UTC, smirnovmykyta reviewed
Лучше поменять @Autowired на конструктор.

2020-12-06 15:31 UTC, Artemiy555 requested changes

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +                    + "http://localhost:8080/confirm-account?token=" + token);//поменять ссылку после деплоя
Думаю стоит вынести в константу

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +    public ResponseEntity<?> sendConfirmationEmail(User user) {
Логику стоит вынести в отдельный сервис

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +    public ResponseEntity<?> sendConfirmationEmail(User user) {
Так же, не думаю что этот метод будет принимать "User", для этого стоит создать новый объект. Аля "ConfirmationUserRequest". Так же думаю стоит добавить аннотации  "@Valid @RequestBody".

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +        User existingUser = userRepository.getUserByEmail(user.getEmail());
Можем не создавать объект юзер, ибо он используется только в одном месте

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +            UserDetailsImpl userDetailsImpl = new UserDetailsImpl(user);
Думаю такая запись будет уместнее UserDetails userDetails = new UserDetailsImpl(user);

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +            SimpleMailMessage mailMessage = new SimpleMailMessage();
У этого класса, нету конструктора который бы принимал все параметры что ниже?

2020-12-06 15:31 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +                    + "http://localhost:8080/confirm-account?token=" + token);//поменять ссылку после деплоя
Где класс метод реализации "/confirm-account"?

2020-12-06 15:33 UTC, Artemiy555 commented on src/main/java/org/zipli/socknet/controller/AuthController.java
> +                    + "http://localhost:8080/confirm-account?token=" + token);//поменять ссылку после деплоя
точнее в в пропертя

2020-12-07 11:14 UTC, andrewpikozh approved these changes

2020-12-07 11:14 UTC, Artemiy555 approved these changes

2020-12-07 12:07 UTC, jtfactum approved these changes

2020-12-07 12:12 UTC, YaroslavSemeniuk approved these changes

2020-12-07 13:45 UTC, smirnovmykyta approved these changes

2020-12-07 14:47 UTC, jtfactum approved these changes

2020-12-07 17:14 UTC, merged